### ISSUE TITLE
Upgrade to ESM

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/array-shuffle#6]
I see this package is still using commonJS. I could try my hand at making a PR that converts it to ESM.
Let me know if you'd like me to try. (I'd take inspiration of your other modules and blog post on ESM)

**Comment by sindresorhus** [comment]
I prefer doing it myself.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/array-shuffle/releases/tag/v3.0.0
